<?php
use Phalconeer\FormValidator as This;

return [
    This\Factory::MODULE_NAME   => [
        'dateFormats'     => [
            'Y-m-d',
            'Y.m.d.',
            'Ymd',
            'Y/m/d',
            'd-m-Y',
            'd.m.Y.',
            'd/m/Y',
        ],
        'timeFormats'       => [
            'Y-m-d H:i:s.u',
            'Y-m-d H:i:s.u\Z',
            'Y-m-d H:i:s',
            'Y-m-d H:i:s\Z',
            'Y.m.d. H:i:s.u',
            'Y.m.d. H:i:s.u\Z',
            'Y.m.d. H:i:s',
            'Y.m.d. H:i:s\Z',
            'Ymd His.u',
            'Ymd His.u\Z',
            'Ymd His',
            'Ymd His\Z',
            'Y/m/d H:i:s.u',
            'Y/m/d H:i:s.u\Z',
            'Y/m/d H:i:s',
            'Y/m/d H:i:s\Z',
            'd-m-Y H:i:s.u',
            'd-m-Y H:i:s.u\Z',
            'd-m-Y H:i:s',
            'd-m-Y H:i:s\Z',
            'd.m.Y. H:i:s.u',
            'd.m.Y. H:i:s.u\Z',
            'd.m.Y. H:i:s',
            'd.m.Y. H:i:s\Z',
            'd/m/Y H:i:s.u',
            'd/m/Y H:i:s.u\Z',
            'd/m/Y H:i:s',
            'd/m/Y H:i:s\Z',
            'Y-m-d\TH:i:s.u',
            'Y-m-d\TH:i:s.u\Z',
            'Y-m-d\TH:i:s',
            'Y-m-d\TH:i:s\Z',
            'Y.m.d.\TH:i:s.u',
            'Y.m.d.\TH:i:s.u\Z',
            'Y.m.d.\TH:i:s',
            'Y.m.d.\TH:i:s\Z',
            'Ymd\THis.u',
            'Ymd\THis.u\Z',
            'Ymd\THis',
            'Ymd\THis\Z',
            'Y/m/d\TH:i:s.u',
            'Y/m/d\TH:i:s.u\Z',
            'Y/m/d\TH:i:s',
            'Y/m/d\TH:i:s\Z',
            'd-m-Y\TH:i:s.u',
            'd-m-Y\TH:i:s.u\Z',
            'd-m-Y\TH:i:s',
            'd-m-Y\TH:i:s\Z',
            'd.m.Y.\TH:i:s.u',
            'd.m.Y.\TH:i:s.u\Z',
            'd.m.Y.\TH:i:s',
            'd.m.Y.\TH:i:s\Z',
            'd/m/Y\TH:i:s.u',
            'd/m/Y\TH:i:s.u\Z',
            'd/m/Y\TH:i:s',
            'd/m/Y\TH:i:s\Z',
            'Y-m-d\THis.u',
            'Y-m-d\THis.u\Z',
            'Y-m-d\THis',
            'Y-m-d\THis\Z',
            'Y.m.d.\THis.u',
            'Y.m.d.\THis.u\Z',
            'Y.m.d.\THis',
            'Y.m.d.\THis\Z',
            'Y/m/d\THis.u',
            'Y/m/d\THis.u\Z',
            'Y/m/d\THis',
            'Y/m/d\THis\Z',
            'd-m-Y\THis.u',
            'd-m-Y\THis.u\Z',
            'd-m-Y\THis',
            'd-m-Y\THis\Z',
            'd.m.Y.\THis.u',
            'd.m.Y.\THis.u\Z',
            'd.m.Y.\THis',
            'd.m.Y.\THis\Z',
            'd/m/Y\THis.u',
            'd/m/Y\THis.u\Z',
            'd/m/Y\THis',
            'd/m/Y\THis\Z',
        ]
    ]
];